### ISSUE TITLE
The name 'Router' is defined in the libraries '

### ISSUE THREAD

**Issue by vipuluthaiah** [imSanjaySoni/Inshorts-Clone-The-News-App#7]
The name 'Router' is defined in the libraries 'package:flutter/src/widgets/router.dart' and 'package:inshort_clone/routes/routesgr.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
![image](https://user-images.githubusercontent.com/45168922/101802816-e074f980-3b35-11eb-93d4-18fcbd0f88cd.png)
![image](https://user-images.githubusercontent.com/45168922/101802854-ecf95200-3b35-11eb-90a1-12905e7debc8.png)

**Comment by imSanjaySoni** [comment]
Hey, this error comes with the new update of  Flutter SDK, because the Router is a preexisting class of SDK.

**You can fix it in two ways..**

`lib/routes/routes.dart`
-  replace the Router class with a different name and run the build_runner command, and replace all imports with the newly generated `routes.gr.dart` file.

-  ![IMG20201218231159.jpg](https://user-images.githubusercontent.com/20748185/102644401-bdc29080-4186-11eb-9ca1-013a38eddee7.jpg)

**Comment by vipuluthaiah** [comment]
Yeh i have already done that..But m8 it works on debug ,But when i run (flutter build apk) apk have many problem

**Comment by vipuluthaiah** [comment]
Like only some features are loading .Eg:Only news load rest there is  no option to go back

**Comment by vipuluthaiah** [comment]
![Screenshot_20201219-112807](https://user-images.githubusercontent.com/45168922/102682205-b8e4f780-41ed-11eb-8782-cebcd29a19e0.jpg)
this is the apk .I cant see the back button and many other features r missing

**Comment by vipuluthaiah** [comment]
![image](https://user-images.githubusercontent.com/45168922/102682217-dc0fa700-41ed-11eb-95a7-e5a69ca5c097.png)
![image](https://user-images.githubusercontent.com/45168922/102682229-ea5dc300-41ed-11eb-89fc-228c9b2bac67.png)
![image](https://user-images.githubusercontent.com/45168922/102682232-f053a400-41ed-11eb-9895-5b9f3a70b566.png)
